<?php

namespace App\Models;

class Circle extends Point
{
    private int $radius;

    /**
     * @param int $x
     * @param int $y
     * @param int $radius
     */
    public function __construct(int $x, int $y, int $radius)
    {
        parent::__construct($x, $y);
        $this->radius = $radius;
    }

    protected function draw(): void
    {
        parent::draw(); // TODO: Change the autogenerated stub
    }


}
