<?php

namespace App\Models;

class Ellipse extends Circle
{
    public function __construct(int $x, int $y, int $radius)
    {
        parent::__construct($x, $y,$radius);
    }

    protected function draw(): void
    {
        parent::draw(); // TODO: Change the autogenerated stub
    }


}
