<?php

namespace App\Models;

class Rectangle extends Square
{
    private int $width;

    /**
     * @param int $width
     */
    public function __construct(int $x1, int $y1, int $x2, int $y2, int $height, int $width)
    {
        parent::__construct($x1, $y1, $x2, $y2, $height);
        $this->width = $width;
    }

    protected function draw(): void
    {
        parent::draw(); // TODO: Change the autogenerated stub
    }


}
