<?php

namespace App\Models;

class Section extends Point
{
    private Point $secondPoint;

    /**
     * @param int $x1
     * @param int $y1
     * @param int $x2
     * @param int $y2
     */
    public function __construct(int $x1, int $y1, int $x2, int $y2)
    {
        parent::__construct($x1, $y1);
        $this->secondPoint = new Point($x2, $y2);
    }

    protected function draw(): void
    {
        parent::draw(); // TODO: Change the autogenerated stub
    }


}
