<?php

namespace App\Models;

class Square extends Point
{
    private Point $rightPoint;
    private int $height;

    /**
     * @param int $x1
     * @param int $y1
     * @param int $x2
     * @param int $y2
     * @param int $height
     */
    public function __construct(int $x1, int $y1, int $x2, int $y2, int $height)
    {
        parent::__construct($x1, $y1);
        $this->rightPoint = new Point($x2, $y2);
        $this->height = $height;
    }


    protected function draw(): void
    {
        parent::draw(); // TODO: Change the autogenerated stub
    }


}
