<?php

namespace App\Models;

class Triangle extends Point
{
    private Point $secondPoint;
    private Point $thirdPoint;

    /**
     * @param int $x1
     * @param int $x1
     * @param int $x2
     * @param int $y2
     * @param int $x3
     * @param int $y3
     */
    public function __construct(int $x1, int $y1, int $x2, int $y2, int $x3, int $y3)
    {
        parent::__construct($x1, $y1);
        $this->secondPoint = new Point($x2, $y2);
        $this->thirdPoint = new Point($x3, $y3);
    }

    protected function draw(): void
    {
        parent::draw(); // TODO: Change the autogenerated stub
    }


}
